### ISSUE TITLE
Add MOTD action

### ISSUE THREAD

**Issue by bjarkiarmanns** [SDiFI/sdifi_rasa_akranes#42]
Add 'MOTD' intent and action for sending user greeting at start of conversation. The relevant greeting - based on the date, e.g. Christmas, Easter - should be extracted from a .yml file via a custom action (or depending on the .yml file structure, can possibly just be listed as a normal response in a separate file).

**Comment by lumpidu** [comment]
As the MOTD could also be e.g. executing querying a Chuck Norris joke of the day API, we should add an appropriate custom action for it. Also we need to add a language slot, so that the API can return the appropriate answer.


Here is the return value definition:

```json
{
	"motd": {
		"language": "is-IS",
		"motd": ["Hæ! Mánudagur er ný byrjun. ",
			       "Hvað get ég hjálpað þér með í dag"
		]
	}
}
```

The yaml file should have a form like that:

```yaml
motd:
  - date_range:
      start: 2023-04-24
      end: 2023-04-24
    messages:
      de-DE:
        - Hallo! Montag ist ein frischer Start.
        - Womit kann ich Ihnen heute behilflich sein?
      is-IS:
        - Hæ! Mánudagur er ný byrjun. 
        - Hvað get ég hjálpað þér með í dag?
      en-EN:
        - Hello! Monday is a fresh start. 
        - What can I help you with today?
  - date_range:
      start: 2023-05-01
      end: 2023-05-07
    messages:
      de-DE:
        - Hallo! Der Mai bringt Wachstum und Erneuerung.
        - Womit kann ich Ihnen heute behilflich sein?
      is-IS:
        - Hæ! Maí færir vöxt og endurvæðingu.
        - Hvað get ég aðstoðað þig með í dag?
      en-EN:
        - Hello! May brings growth and renewal.
        - What can I assist you with today?
  default:
    messages:
      de-DE:
        - Guten Tag! Ich bin Ihr Chatbot. Wie kann ich Ihnen heute helfen?
      is-IS:
        - Góðan dag! Ég er spjallforritið þitt. Hvernig get ég aðstoðað þig í dag?
      en-EN:
        - Good day! I'm your chatbot. How can I assist you today?
```

And the custom action needs to find the correct answer depending on the current date.
